version: '3.6'

services:
  mojocker:
    build:
      context: .
      dockerfile: Dockerfile
    image: purplelemons/mojocker
    ipc: host
    restart: unless-stopped
    volumes:
      - mojocker:/opt/mojocker
    tty: true
    init: true

volumes:
  mojocker: {}
